### ISSUE TITLE
Segmentation fault when tokenizing number

### ISSUE THREAD

**Issue by genius257** [DcodingTheWeb/EasyCodeIt#3]
Caused by the following lines:

https://github.com/DcodingTheWeb/EasyCodeIt/blob/920ff107634b5ef2e6b584b189d3732e5d8df995/parse.c#L270

https://github.com/DcodingTheWeb/EasyCodeIt/blob/920ff107634b5ef2e6b584b189d3732e5d8df995/parse.c#L272

**Comment by TheDcoder** [comment]
Thanks for the report, can you give me an input which can reproduce this issue? I have tested this code and it shouldn't cross any boundaries.

**Comment by genius257** [comment]
```c
#include <stdio.h>
#include <stdlib.h>
#include <stdnoreturn.h>
#include "utils.h"
#include "parse.h"

int main(void)
{
    parse("Global $a = 0\n");
    return EXIT_SUCCESS;
}
```

Result:
```
Segmentation fault
```

If you don't get the same result, it may be my setup.
Currently using [wandbox](https://wandbox.org/#), with the C11(GNU) selected as the Compiler.

It does pass with strings, so i assume it is a problem 😄

**Comment by TheDcoder** [comment]
I am unable to reproduce the issue, just tested with a fresh build from `master`:
```
TheDcoder@arch /t/e/build> ./eci /tmp/eci.txt
---### TOKEN ###---
Type: Word
Data: <Keyword>Global
---### TOKEN ###---
Type: Variable
Data: a
---### TOKEN ###---
Type: Operator
Data: =
---### TOKEN ###---
Type: Number
Data: 0
TheDcoder@arch /t/e/build> cat /tmp/eci.txt
Global $a = 0
```

By the way, the lines you mentioned in the first post exist because `strtod` only stops on an invalid or `NUL` character, I didn't want to `strtod` to cross the token's boundary so I temporarily replace the next-to-last character with a null terminator and then restore it once the function is done :relaxed:

**Comment by genius257** [comment]
Seems to be my mistake. The issue cannot be reproduced within my alpine-gcc docker container.
Must be something wrong with the online solution i was using. Sorry for wasting your time ^^'

**Comment by TheDcoder** [comment]
No problem, thanks for trying out the code.
